### ISSUE TITLE
Migration to docsy theme

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#746]
Jaeger website today is using a completely custom theme. This creates a maintenance headache as we run into various layout bugs (e.g. #744, #745). We also have issues with some old dependencies for CASS like bulma (#730).

I looked around in other CNCF projects and noticed that both OpenTelemetry and Kubernetes websites are using https://github.com/google/docsy theme, which is likely much better supported.

Of course, it's not a very trivial job to replace the theme, as we also have plenty of CSS customizations that we would want to keep.  So before we really decide to do that we need some investigation, e.g. just trying out enabling the docsy theme and spot-checking what would break in Jaeger as a result, and collect the findings into a report.

One thing we'd need to do is customize the color schemes to match the existing Jaeger website (https://www.docsy.dev/docs/adding-content/lookandfeel/)

## Docsy preview

- https://docsy--jaegertracing.netlify.app/

---

### Questions to clarify requirements & design objectives

- [x] #911 - no
- [ ] #892 

### Prep & clean up

- [x] #894 
- [x] #895 
- [x] #896
- [x] Consolidate NPM packages and more:
  - [x] #903
  - [x] #905
- [x] #904
- [x] #901
- [x] #908
- [x] #915
- [x] #985
  - [x] #910

### Tasks

- [x] Add Docsy as NPM package - #903 
- [x] #909
- [x] #912
- [x] Set up the `docsy` branch:
  - [x] Create [docsy](https://github.com/jaegertracing/documentation/tree/docsy) branch
  - [x] Adjust build instructions to use `hugo.docsy` config
  - [x] Configure `docsy` branch deploys and PR previews. Done, see https://app.netlify.com/projects/jaegertracing/configuration/deploys#branches-and-deploy-contexts
- [x] #913 
- [x] Homepage
  - [x] #995
  - [x] #997
  - [x] #1001
- [x] #998
- [x] #1000 
- [x] #1002 
- [x] #1003 
- [x] #1004 
- [x] Favicon
- Done! 🎉 Next steps via #1024

**Comment by Dindihub** [comment]
Hi, @yurishkuro Did you get help with this issue? I worked on a similar project for [theupdateframework](https://github.com/theupdateframework/theupdateframework.io/pull/105#issuecomment-2408643170) during my LFX mentorship program Term 2 2024. I would be glad to assist.

**Comment by yurishkuro** [comment]
@Dindihub  We do need help.

**Comment by chalin** [comment]
/cc @nate-double-u, since we talked about this during our techdocs call this morning. @yurishkuro - we were curious if you had create a ticket for this?

Btw, @Dindihub contributed to the base work of the following:

- https://github.com/theupdateframework/theupdateframework.io/pull/105

I'm about to wrap up the Docsy migration for the in-toto project. I plan to look into what would be involved for this project. Maybe @Dindihub will look into it before then too.

**Comment by yurishkuro** [comment]
> we were curious if you had create a ticket for this?

@chalin sorry, I didn't follow - are you asking about the JIRA ticket I opened long time ago? That one was more about informational structure review / recommendations (especially since we just rolled out new documentation for Jaeger v2).

**Comment by chalin** [comment]
Thanks for the context. I was wondering if you had opened a new ticket that I might not have been aware of (not an obligation of course).

**Comment by yurishkuro** [comment]
@chalin fwiw upgrading to docsy would be much higher priority

**Comment by chalin** [comment]
@yurishkuro - we're discussing this as _possibly_ in scope for 2025. Btw, I'd remove the `good first issue` label since this work requires a lot of expertise, and is an undertaking that will span weeks.

**Comment by chalin** [comment]
@yurishkuro - before year's end. Either @nate-double-u or I will reach out (possibly via Slack and or the Jira ticket open for this repo).

**Comment by chalin** [comment]
@yurishkuro - in case you are wondering: I'm spending some initial time studying the current website information architecture (IA), custom theme, layouts, etc. Working on peripheral tasks (like external link checking), not directly related to the Docsy migration, is a practical and useful way for me to get a deeper understand of the site features, so that I can better prepare questions for you, and plan the migration.

Can you assign this issue to me?

**Comment by chalin** [comment]
@yurishkuro - FYI, I'll be OOO for a few weeks. I'll be resuming the migration as soon as I can.

**Comment by chalin** [comment]
@yurishkuro - btw, I've noticed that the new site has better Lighthouse ratings, e.g.:

> <img width="674" height="356" alt="Image" src="https://github.com/user-attachments/assets/12780dd5-daa3-4f84-b8ec-c88f5b6e821e" />

/cc @nate-double-u

**Comment by chalin** [comment]
I'm glad that you like it. I've tagged some very useful Docsy improvements to upstream. ✨  Thanks for your patience in getting this completed. I'm pleased with the result too. 🙌🏻 As I upstream changes to Docsy, I'll update this repo and remove the Docsy overrides. That will help reduce technical debt and increase ease of maintenance and Docsy upgrades in the long term.
